services:
  redis:
    image: redis:7-alpine
    container_name: unbound-redis
    command: redis-server --save 60 1 --loglevel warning --rdbcompression no --rdbchecksum no --maxmemory 128mb --maxmemory-policy allkeys-lru --slowlog-max-len 16
    volumes:
      - "./redis:/data"
    restart: always

  unbound:
    image: unbound:latest
    container_name: unbound
    network_mode: "host"
    depends_on:
      - redis
    ports:
      - target: 8553
        published: 8553
        protocol: tcp
      - target: 8553
        published: 8553
        protocol: udp
    volumes:
      - "./config:/config:ro"
      - "./root.hints:/root.hints"
    restart: always
